# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: "echo starting Slaves"
  
  config.vm.define "ansible8" do |ansible8|
    ansible8.vm.box_check_update = false
    ansible8.vm.box = "ubuntu/xenial64"
    ansible8.vm.network "forwarded_port", guest: 301, host: 3010
    ansible8.vm.network "private_network", ip: "192.168.110.10"
	ansible8.vm.provision "shell", path: "ansible.sh"
    ansible8.vm.provider "virtualbox" do |vb1|
	vb1.name = "Ansible8"
	vb1.memory = 2048
    vb1.cpus = 2
	end
  end
 
 
  config.vm.define "dev8" do |dev8|
    dev8.vm.box_check_update = false
    dev8.vm.box = "ubuntu/xenial64"
    dev8.vm.network "forwarded_port", guest: 303, host: 3030
    dev8.vm.network "private_network", ip: "192.168.110.30"
	dev8.vm.provision "shell", path: "lamp.sh"
    dev8.vm.provider "virtualbox" do |vb3|
	vb3.name = "Dev8"
	vb3.memory = 2048
    vb3.cpus = 2
	end
  end
  
  config.vm.define "test8" do |test8|
    test8.vm.box_check_update = false
    test8.vm.box = "kreator/trusty64-docker"
    test8.vm.network "forwarded_port", guest: 304, host: 3040
    test8.vm.network "private_network", ip: "192.168.110.40"
	#test8.ssh.username = "root"
	#test8.ssh.password = "ubuntu"
	test8.vm.provision "shell", path: "sonar.sh"
    test8.vm.provider "virtualbox" do |vb4|
	vb4.name = "Test8"
	vb4.memory =4096
    vb4.cpus = 2
	end
  end
  
  config.vm.define "docker3" do |docker3|
	docker3.vm.box_check_update = false
	docker3.vm.box = "kreator/trusty64-docker"
	docker3.vm.network "private_network", ip: "192.168.110.50"
	docker3.vm.network "forwarded_port", guest: 305, host: 3050
	#docker3.ssh.username = "vagrant"
	#docker3.ssh.password = "vagrant"
	docker3.vm.provision "shell", path: "javaonly.sh"
	docker3.vm.provider "virtualbox" do |vb5|
	vb5.name = "Docker3"
	vb5.memory =2048
    vb5.cpus = 2
	end
  end	
end
