---

- hosts: docker
  remote_user: root
  sudo: yes
  tasks:

    - name: Build the image
      shell: docker build -t app /dockerfolder

    - name: Run the local registry
      shell: docker run -d -p 5000:5000 --restart=always --name=registry registry:latest