#sintassi ruby

Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: "echo starting Jenkins Master"
  
  config.vm.define "JenkinsVM" do |jenkins|
    jenkins.vm.box_check_update = false
    jenkins.vm.box = "ubuntu/xenial64"
    jenkins.vm.network "forwarded_port", guest: 80, host: 8690
    jenkins.vm.network "private_network", ip: "192.168.110.20"
	jenkins.vm.provision "shell", path: "jenkins.sh"
    jenkins.vm.provider "virtualbox" do |vb1|
	vb1.name = "JenkinsVM"
	vb1.memory = 2048
    vb1.cpus = 2
	end
  end
  
  config.trigger.after :up do
   system('./myscript.bat')
  end
  
  config.trigger.after :halt do
   system('./stopslave.bat')
  end
  
end
